Gradle was updated from 7.4.2 to 7.5.1 to fix issue: ``` > Task :sentry-kotlin-multiplatform:generateDebugRFile FAILED
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':sentry-kotlin-multiplatform:generateDebugRFile'.
> Multiple build operations failed.
      java.nio.file.NoSuchFileException: /Users/leokapanen/.gradle/caches/transforms-3/18c9754c5414418e9f155d9c14549b76/results.bin
      java.nio.file.NoSuchFileException: /Users/leokapanen/.gradle/caches/transforms-3/554166ad08a7b2e04ac0db776a5a23c1/results.bin
      java.nio.file.NoSuchFileException: /Users/leokapanen/.gradle/caches/transforms-3/4e97ff2e1aa4ecf0e3b2f5d019d1a52a/results.bin
   > java.nio.file.NoSuchFileException: /Users/leokapanen/.gradle/caches/transforms-3/18c9754c5414418e9f155d9c14549b76/results.bin
   > java.nio.file.NoSuchFileException: /Users/leokapanen/.gradle/caches/transforms-3/554166ad08a7b2e04ac0db776a5a23c1/results.bin
   > java.nio.file.NoSuchFileException: /Users/leokapanen/.gradle/caches/transforms-3/4e97ff2e1aa4ecf0e3b2f5d019d1a52a/results.bin
```